### ISSUE TITLE
作者您好，请问可以求一份与奶龙相似物品的数据集吗

### ISSUE THREAD

**Issue by epp233** [ZreXoc/nailong-classification#4]
我在您给出的huggingface链接里获取到的数据集只有奶龙和表情包的，我的模型训练完后对一些奶龙相似物品的甄别不强，想求一份与奶龙相似物品的数据集，网上找了很久都找不到，还望伸手援助，感激不尽~

**Comment by ZreXoc** [comment]
已上传，具体见 https://huggingface.co/datasets/XiC1/nailong-dataset/blob/main/data/source.tar
其实都是自己想关键词从百度和bing爬下来的
