### ISSUE TITLE
数据集配置问题

### ISSUE THREAD

**Issue by YuanzeWWW** [ZreXoc/nailong-classification#5]
作者您好，我是一名计算机新手QAQ，在按照您的数据集划分结构后，在您给出的数据集下载链接中找不到temp.py所对应的代码，请问这个temp.py是如何使用的？同时我在测试的时候，发现在vali.py中低52 行 model_path='./out/1103-011540/model_best.pth' 其实在文件中并没有所对应的文件，请问是要自己创建吗？十分感谢！！！

**Comment by ZreXoc** [comment]
`temp.py`是我自己测试用的，没有实际作用，readme忘改了

> 从 https://huggingface.co/XiC1/nailong_model 下载模型
> 修改vali.py中model_path

从上面的连接下载模型放在文件夹里，然后修改路径

**Comment by YuanzeWWW** [comment]
感谢作者您能真的回复我UWU！！！在按照您说的下载模型文件后，我分别运行了train.py和vali.py，结果如下图所示（为了节省时间，train.py我只跑了一代），请问这样就是跑完了吗，还是说有别的步骤？同时我对数据集下载链接中的一些脚本文件不是很会使用,请问这些脚本需要使用吗？最后再次谢谢大佬能抽出时间解答我的疑问QAQ！！！

![image](https://github.com/user-attachments/assets/fbbaa95d-86a4-4dc4-bf1f-6543cace3827)
![image](https://github.com/user-attachments/assets/136f5de1-86fb-49ff-8fcb-e779abfa1d9f)

**Comment by ZreXoc** [comment]
客气话就不必了

脚本是我处理数据用的，不必不使用； 训完一个epoch后就可以在 `out/` 下找到相应模型，默认是每5个epoch保存一次，同时保存准确率最好的模型，一般会多训几轮直到loss不再下降或者出现过拟合现象

**Comment by YuanzeWWW** [comment]
嗯嗯，所以有可视化输出吗？比如在data的结构里出现分类后的图片这样之类的

**Comment by YuanzeWWW** [comment]
作者您好，请问data目录下除了train和test在您给出的数据集下载链接中有，其他的那些目录是要自己配置吗？还是说是在运行模型时来存放模型的分类结果的？然后就是我把您给出的vali.py中注释掉的可视化部分给想办法整回来了（用GPT），然后发现是最终预测概率和对应的频率，请问如何判模型是否真的预测正确呢，我想通过这个做一个预测结果的混淆矩阵的可视化，谢谢您了！

**Comment by ZreXoc** [comment]
> 作者您好，请问data目录下除了train和test在您给出的数据集下载链接中有，其他的那些目录是要自己配置吗？还是说是在运行模型时来存放模型的分类结果的？然后就是我把您给出的vali.py中注释掉的可视化部分给想办法整回来了（用GPT），然后发现是最终预测概率和对应的频率，请问如何判模型是否真的预测正确呢，我想通过这个做一个预测结果的混淆矩阵的可视化，谢谢您了！

所有数据都在hf里面了，只要有train和test下有`nailong`和`other`这两个目录即可; 模型仅给出预测结果，你可以自己给图片人工标注分出正负样本

---

另外，本项目仅一时兴起做着玩的，代码有诸多不规范之处，并不适合学习 😕
